#
# Gramps - a GTK+/GNOME based genealogy program
#
# Copyright (C) 2000-2007 Donald N. Allingham
# Copyright (C) 2008      Brian G. Matherly
# Copyright (C) 2010      Jakim Friant
# Copyright (C) 2025      (contributor)
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#

"""Tools/Database Processing/Extract Event Descriptions from Event Data"""

# ------------------------
# Python modules
# ------------------------
import logging

# ------------------------
# Gramps modules
# ------------------------
import gi

gi.require_version("Gtk", "3.0")
from gi.repository import Gtk

from gramps.gen.const import GRAMPS_LOCALE as glocale
from gramps.gen.lib import EventRoleType
from gramps.gen.db import DbTxn
from gramps.gen.utils.db import family_name
from gramps.gui.plug import tool
from gramps.gen.display.name import displayer as name_displayer

# ------------------------
# Gramps specific
# ------------------------

_ = glocale.translation.gettext
ngettext = glocale.translation.ngettext  # else "nearby" comments are ignored

LOG = logging.getLogger(__name__)

# -------------------------------------------------------------------------
#
# Mode constants
#
# -------------------------------------------------------------------------
MODE_ADD = "add"
MODE_REMOVE = "remove"

# feature requests 2356, 1658: avoid genitive form
EVENT_FAMILY_STR = _("%(event_name)s of %(family)s")

# feature requests 2356, 1658: avoid genitive form
EVENT_PERSON_STR = _("%(event_name)s of %(person)s")


#------------------------------------------------------------
#
# EventNamesDialog
#
#------------------------------------------------------------
class EventNamesDialog(Gtk.Dialog):
    """
    Pre-run dialog that lets the user choose between adding auto-generated
    event descriptions to blank events, or removing descriptions that were
    previously added by this tool — before any undo-history warning fires.

    :param parent: Parent ``Gtk.Window`` or ``None``.
    """

    def __init__(self, parent: Gtk.Window | None = None) -> None:
        super().__init__(
            title=_("Extract Event Descriptions"),
            transient_for=parent,
            modal=True,
            destroy_with_parent=True,
        )
        self.set_border_width(12)
        self.set_default_size(480, -1)

        # ── Content area ──────────────────────────────────────────────
        content = self.get_content_area()
        content.set_spacing(12)

        # Icon + explanation row
        hbox = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=12)
        icon = Gtk.Image.new_from_icon_name(
            "dialog-information", Gtk.IconSize.DIALOG
        )
        hbox.pack_start(icon, False, False, 0)

        explain = Gtk.Label()
        explain.set_markup(
            _(
                "<b>Extract Event Descriptions</b>\n\n"
                "This tool can fill in blank event descriptions using the "
                "name of the primary person or family associated with each "
                "event.\n\n"
                "Choose an action below, then click <i>Proceed</i>."
            )
        )
        explain.set_line_wrap(True)
        explain.set_max_width_chars(52)
        explain.set_xalign(0.0)
        hbox.pack_start(explain, True, True, 0)
        content.pack_start(hbox, False, False, 0)

        # Separator
        content.pack_start(Gtk.Separator(), False, False, 4)

        # Radio buttons
        self._rb_add = Gtk.RadioButton.new_with_mnemonic(
            None,
            _(
                "_Add descriptions to events that currently have a blank "
                "description (default)"
            ),
        )
        self._rb_remove = Gtk.RadioButton.new_with_mnemonic_from_widget(
            self._rb_add,
            _(
                "_Remove descriptions that appear to have been generated by "
                "this tool (reverses a previous run)"
            ),
        )

        rb_box = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=6)
        rb_box.pack_start(self._rb_add, False, False, 0)
        rb_box.pack_start(self._rb_remove, False, False, 0)
        content.pack_start(rb_box, False, False, 0)

        # Hint label (updates when selection changes)
        self._hint = Gtk.Label()
        self._hint.set_line_wrap(True)
        self._hint.set_max_width_chars(52)
        self._hint.set_xalign(0.0)
        context = self._hint.get_style_context()
        context.add_class("dim-label")
        content.pack_start(self._hint, False, False, 0)
        self._update_hint()

        self._rb_add.connect("toggled", self._cb_radio_toggled)

        # ── Action buttons ────────────────────────────────────────────
        self.add_button(_("_Stop"), Gtk.ResponseType.CANCEL)
        proceed_btn = self.add_button(_("_Proceed with the Tool"), Gtk.ResponseType.OK)
        proceed_btn.get_style_context().add_class("suggested-action")
        self.set_default_response(Gtk.ResponseType.OK)

        content.show_all()

    # ------------------------------------------------------------------
    # Callbacks
    # ------------------------------------------------------------------

    def _cb_radio_toggled(self, widget: Gtk.RadioButton) -> None:
        """
        Update the hint text when the radio selection changes.

        :param widget: The radio button that emitted the signal.
        """
        self._update_hint()

    def _update_hint(self) -> None:
        """
        Refresh the hint label to match the currently selected mode.
        """
        if self._rb_add.get_active():
            self._hint.set_markup(
                _(
                    "<i>Events whose description is already set will not be "
                    "changed.  This action can be undone via Edit → Undo.</i>"
                )
            )
        else:
            self._hint.set_markup(
                _(
                    "<i>Only descriptions that match the pattern generated by "
                    "this tool ("
                    "<tt>Event type of Person/Family</tt>"
                    ") will be cleared.  "
                    "Descriptions you have written manually will not be "
                    "touched.  This action can be undone via Edit → Undo.</i>"
                )
            )

    # ------------------------------------------------------------------
    # Public helpers
    # ------------------------------------------------------------------

    def get_mode(self) -> str:
        """
        Return the mode selected by the user.

        :returns: ``MODE_ADD`` or ``MODE_REMOVE``.
        """
        return MODE_ADD if self._rb_add.get_active() else MODE_REMOVE


#------------------------------------------------------------
#
# EventNames
#
#------------------------------------------------------------
class EventNames(tool.BatchTool):
    """
    Look for events that do not have a description, and build the description
    from the item that contains it.

    Looks for a PRIMARY role type for events attached to a person, and a
    FAMILY role for an event that is attached to a family.

    A pre-run dialog (``EventNamesDialog``) now replaces the bare undo-history
    warning and additionally offers the reciprocal action of clearing
    auto-generated descriptions from a prior run.
    """

    def __init__(
        self, dbstate, user, options_class, name, callback=None
    ) -> None:
        self.user = user
        tool.BatchTool.__init__(self, dbstate, user, options_class, name)
        if not self.fail:
            self._show_dialog_and_run()

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _show_dialog_and_run(self) -> None:
        """
        Present ``EventNamesDialog``, then delegate to the appropriate runner.
        """
        parent_window = (
            self.user.uistate.window
            if hasattr(self.user.uistate, "window")
            else None
        )

        dlg = EventNamesDialog(parent=parent_window)
        response = dlg.run()
        mode = dlg.get_mode()
        dlg.destroy()

        if response != Gtk.ResponseType.OK:
            LOG.debug("EventNames: user cancelled the pre-run dialog.")
            return

        if mode == MODE_ADD:
            self._run_add(parent_window)
        else:
            self._run_remove(parent_window)

    def _run_add(self, parent_window: Gtk.Window | None) -> None:
        """
        Add auto-generated descriptions to events that have a blank description.

        :param parent_window: Parent window for result dialogs.
        """
        with DbTxn(_("Event name changes"), self.db, batch=True) as trans:
            self.db.disable_signals()
            change = False
            counter = 0

            with self.user.progress(
                _("Extract Event Description"), "", 2
            ) as step:
                for person in self.db.iter_people():
                    for event_ref in person.get_event_ref_list():
                        if event_ref.get_role() == EventRoleType.PRIMARY:
                            event = self.db.get_event_from_handle(
                                event_ref.ref
                            )
                            if not event.get_description():
                                person_event_name(event, person)
                                self.db.commit_event(event, trans)
                                change = True
                                counter += 1
                    step()

                for family in self.db.iter_families():
                    for event_ref in family.get_event_ref_list():
                        if event_ref.get_role() == EventRoleType.FAMILY:
                            event = self.db.get_event_from_handle(
                                event_ref.ref
                            )
                            if not event.get_description():
                                family_event_name(event, family, self.db)
                                self.db.commit_event(event, trans)
                                change = True
                                counter += 1
                    step()

            self.db.enable_signals()
            self.db.request_rebuild()

        if change:
            message = ngettext(
                "{quantity} event description has been added",
                "{quantity} event descriptions have been added",
                counter,
            ).format(quantity=counter)
            self.user.info(
                _("Modifications made"), message, parent=parent_window
            )
        else:
            self.user.info(
                _("No modifications made"),
                _("No event description has been added."),
                parent=parent_window,
            )

    def _run_remove(self, parent_window: Gtk.Window | None) -> None:
        """
        Clear event descriptions that appear to have been generated by a
        previous run of this tool (i.e. those matching the
        ``"<EventType> of <Name>"`` pattern).

        Descriptions that do not match the generated pattern are left intact.

        :param parent_window: Parent window for result dialogs.
        """
        with DbTxn(_("Event name removal"), self.db, batch=True) as trans:
            self.db.disable_signals()
            change = False
            counter = 0

            with self.user.progress(
                _("Remove Generated Event Descriptions"), "", 2
            ) as step:
                for person in self.db.iter_people():
                    for event_ref in person.get_event_ref_list():
                        if event_ref.get_role() == EventRoleType.PRIMARY:
                            event = self.db.get_event_from_handle(
                                event_ref.ref
                            )
                            if _matches_person_pattern(event, person):
                                event.set_description("")
                                self.db.commit_event(event, trans)
                                change = True
                                counter += 1
                    step()

                for family in self.db.iter_families():
                    for event_ref in family.get_event_ref_list():
                        if event_ref.get_role() == EventRoleType.FAMILY:
                            event = self.db.get_event_from_handle(
                                event_ref.ref
                            )
                            if _matches_family_pattern(event, family, self.db):
                                event.set_description("")
                                self.db.commit_event(event, trans)
                                change = True
                                counter += 1
                    step()

            self.db.enable_signals()
            self.db.request_rebuild()

        if change:
            message = ngettext(
                "{quantity} generated event description has been removed",
                "{quantity} generated event descriptions have been removed",
                counter,
            ).format(quantity=counter)
            self.user.info(
                _("Modifications made"), message, parent=parent_window
            )
        else:
            self.user.info(
                _("No modifications made"),
                _("No generated event description was found to remove."),
                parent=parent_window,
            )


# -------------------------------------------------------------------------
#
# Support functions
#
# -------------------------------------------------------------------------

def person_event_name(event, person) -> None:
    """
    Build a name for an event based on the primary person's information.

    :param event: The ``Event`` object to update.
    :param person: The ``Person`` object associated with the event.
    """
    if not event.get_description():
        text = EVENT_PERSON_STR % {
            "event_name": str(event.get_type()),
            "person": name_displayer.display(person),
        }
        event.set_description(text)


def family_event_name(event, family, dbase) -> None:
    """
    Build a name for an event based on the family's information.

    :param event: The ``Event`` object to update.
    :param family: The ``Family`` object associated with the event.
    :param dbase: The database instance used to look up family members.
    """
    if not event.get_description():
        text = EVENT_FAMILY_STR % {
            "event_name": str(event.get_type()),
            "family": family_name(family, dbase),
        }
        event.set_description(text)


def _matches_person_pattern(event, person) -> bool:
    """
    Return ``True`` when an event description matches the string that
    :func:`person_event_name` would have produced for *person*.

    :param event: The ``Event`` object to test.
    :param person: The ``Person`` to compare against.
    :returns: ``True`` if the description is a generated one.
    """
    desc = event.get_description()
    if not desc:
        return False
    expected = EVENT_PERSON_STR % {
        "event_name": str(event.get_type()),
        "person": name_displayer.display(person),
    }
    return desc == expected


def _matches_family_pattern(event, family, dbase) -> bool:
    """
    Return ``True`` when an event description matches the string that
    :func:`family_event_name` would have produced for *family*.

    :param event: The ``Event`` object to test.
    :param family: The ``Family`` to compare against.
    :param dbase: The database instance used to look up family members.
    :returns: ``True`` if the description is a generated one.
    """
    desc = event.get_description()
    if not desc:
        return False
    expected = EVENT_FAMILY_STR % {
        "event_name": str(event.get_type()),
        "family": family_name(family, dbase),
    }
    return desc == expected


#------------------------------------------------------------
#
# EventNamesOptions
#
#------------------------------------------------------------
class EventNamesOptions(tool.ToolOptions):
    """
    Define options and provides handling interface.
    """

    def __init__(self, name, person_id=None) -> None:
        tool.ToolOptions.__init__(self, name, person_id)
